// Types generated by hand from docs/API_CONTRACT.md (the source of truth).
// Do NOT invent fields here that the contract does not define. If the UI needs
// something more, the change goes into API_CONTRACT.md first.

export type Provenance = "REAL" | "SIMULATED" | "ASSUMED" | "PREDICTED" | "OBSERVED";
export type Severity = "INFO" | "WARNING" | "HIGH" | "CRITICAL";
export type Role = "OPERATOR" | "SUPERVISOR" | "SAFETY_MANAGER" | "ADMIN";

export interface ErrorEnvelope {
  error: {
    code:
      | "UNAUTHORIZED"
      | "FORBIDDEN"
      | "NOT_FOUND"
      | "VALIDATION_ERROR"
      | "TELEMETRY_STALE"
      | "ML_UNAVAILABLE"
      | "CONFLICT"
      | "INTERNAL";
    message: string;
    detail?: Record<string, unknown>;
  };
}

/** WHAT / WHY / ACTION — the explainability contract used across the product. */
export interface Explanation {
  what: string;
  why: string;
  action: string;
}

export interface User {
  id: string;
  name: string;
  role: Role;
}

export interface LoginResponse {
  access_token: string;
  token_type: "bearer";
  user: User;
}

export interface Operator extends User {
  current_machine_id: string;
  current_shift_id: string;
}

export type MachineStatus = "IDLE" | "OPERATING" | "OFF" | "MAINTENANCE";

export interface Machine {
  id: string;
  type: string;
  model: string;
  site_id: string;
  status: MachineStatus;
  engine_hours: number;
}

export type HealthState = "NORMAL" | "WARNING" | "DEGRADED" | "CRITICAL";

export interface HealthSignal {
  name: string;
  value: number;
  unit: string;
  state: HealthState;
}

export interface MachineHealth {
  machine_id: string;
  state: HealthState;
  health_score: number;
  provenance: Provenance;
  signals: HealthSignal[];
  explanation: Explanation;
}

export interface TelemetryRow {
  idempotency_key?: string;
  timestamp: string;
  machine_id: string;
  operator_id: string;
  engine_hours: number;
  fuel_used: number;
  fuel_rate?: number;
  load_cycles: number;
  idle_time: number;
  cycle_time: number;
  engine_temperature: number;
  hydraulic_pressure: number;
  engine_load: number;
  speed: number;
  latitude: number;
  longitude: number;
  seatbelt_status: "FASTENED" | "UNFASTENED";
  warning_code: string | null;
  machine_state: MachineStatus;
}

export interface TelemetryResponse {
  stale: boolean;
  last_update_age_seconds: number;
  rows: TelemetryRow[];
}

export type TaskState =
  | "SCHEDULED"
  | "STARTED"
  | "IN_PROGRESS"
  | "AT_RISK"
  | "DELAYED"
  | "COMPLETED"
  | "CANCELLED";

export type TaskType = "EXCAVATION" | "LOADING" | "GRADING" | "HAULING" | "TRENCHING";
export type Priority = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";

export interface Task {
  id: string;
  title: string;
  type: TaskType | string;
  priority: Priority;
  site_id: string;
  machine_id: string;
  state: TaskState;
  progress: number;
  scheduled_start: string;
  original_eta: string;
  predicted_eta: string;
  eta_provenance: Provenance;
}

export interface WeatherSnapshot {
  temperature_c: number;
  rainfall_mm: number;
  wind_kph: number;
  visibility_km: number;
  humidity_pct: number;
  condition: string;
}

export interface TaskEvent {
  timestamp: string;
  label: string;
  kind: "STATE" | "ETA" | "SAFETY" | "NOTE";
}

export interface TaskDetail extends Task {
  delay_reason: string | null;
  environment: WeatherSnapshot;
  events: TaskEvent[];
}

export interface EtaPrediction {
  task_id: string;
  predicted_eta: string;
  delta_minutes: number;
  provenance: Provenance;
  explanation: Explanation;
  fallback_used: boolean;
}

export type SafetyEventType =
  | "SEATBELT_UNFASTENED"
  | "PROXIMITY_HAZARD"
  | "RESTRICTED_ZONE_ENTRY"
  | "OVERSPEED"
  | "UNSAFE_SLOPE"
  | "SUDDEN_MOVEMENT";

export interface SafetyEvent {
  id: string;
  timestamp: string;
  type: SafetyEventType;
  severity: Severity;
  machine_id: string;
  operator_id: string;
  location: { lat: number; lng: number };
  telemetry_context: Record<string, unknown>;
  provenance: Provenance;
  recommended_action: string;
  acknowledged: boolean;
}

export type AlertStatus = "CREATED" | "ACTIVE" | "ACKNOWLEDGED" | "RESOLVED" | "ESCALATED";

export interface Alert {
  id: string;
  severity: Severity;
  status: AlertStatus;
  count: number;
  grouped_event_ids: string[];
  summary: string;
  type?: SafetyEventType;
  recommended_action?: string;
  created_at?: string;
}

export interface IncidentTimelineEntry {
  timestamp: string;
  source: "TELEMETRY" | "SAFETY" | "WEATHER";
  label: string;
  detail?: string;
}

export interface Incident {
  id: string;
  machine_id: string;
  operator_id: string;
  type: "NEAR_MISS" | "COLLISION" | "ROLLOVER" | "EQUIPMENT_DAMAGE" | "OTHER";
  description: string;
  occurred_at: string;
  review_status: "OPEN" | "UNDER_REVIEW" | "CLOSED";
  notes: string[];
  timeline: IncidentTimelineEntry[];
}

export type TrainingStatus = "RECOMMENDED" | "IN_PROGRESS" | "COMPLETED" | "NOT_STARTED";

export interface TrainingRecord {
  module_id: string;
  title: string;
  status: TrainingStatus;
  reason: string;
  provenance: Provenance;
  completion: number;
  duration_min?: number;
  format?: "VIDEO" | "SIMULATION" | "INSTRUCTOR";
}

export interface FuelAnalytics {
  fuel_per_hour: number;
  fuel_per_cycle: number;
  idle_fuel_estimate: number;
  baseline_fuel_per_cycle: number;
  provenance: Provenance;
  insight: Explanation;
}

export interface ProductivityAnalytics {
  cycles_per_hour: number;
  idle_percentage: number;
  task_completion_rate: number;
  productive_time_pct: number;
  provenance: Provenance;
  insight: Explanation;
  trend: { t: string; cycles: number; idle: number }[];
}

export interface AssistantResponse {
  answer: string;
  grounded: boolean;
  facts_used: { tool: string; [k: string]: unknown }[];
  provenance: Provenance;
  data_available: boolean;
}

// ── Shift handover (assembled from contract primitives) ──────────────────────
export interface ShiftHandover {
  shift_id: string;
  operator: User;
  machine_id: string;
  generated_at: string;
  tasks_completed: { id: string; title: string }[];
  tasks_remaining: { id: string; title: string; state: TaskState }[];
  machine_health: { state: HealthState; health_score: number };
  safety_events: { count: number; highest: Severity };
  fuel_used_l: number;
  abnormal_behavior: string[];
  maintenance_recommendation: string | null;
  pending_actions: string[];
}

// ── Work-zone (proximity / geofencing view) ──────────────────────────────────
export interface ZoneEntity {
  id: string;
  kind: "MACHINE" | "WORKER" | "VEHICLE" | "RESTRICTED";
  label: string;
  x: number; // metres, relative to the operator's machine at origin
  y: number;
  distance_m?: number;
}

export interface WorkZone {
  machine_id: string;
  threshold_m: number;
  provenance: Provenance;
  entities: ZoneEntity[];
}

// ── WebSocket envelope ───────────────────────────────────────────────────────
export type WsMessage =
  | { type: "SAFETY_ALERT"; payload: Alert }
  | { type: "TELEMETRY_TICK"; payload: { machine_id: string; stale: boolean } & Partial<TelemetryRow> }
  | { type: "ETA_UPDATE"; payload: { task_id: string; predicted_eta: string; delta_minutes?: number } }
  | { type: "TELEMETRY_STALE"; payload: { machine_id: string; age_seconds: number } }
  | { type: "SNAPSHOT"; payload: { active_alerts: Alert[] } }
  | { type: "INSIGHT"; payload: { title: string; explanation: Explanation; severity: Severity } };
