import type { Provenance, Severity } from "@/api/types";

/** Minimal classnames helper — avoids pulling in a dependency for one job. */
export function cx(...parts: Array<string | false | null | undefined>): string {
  return parts.filter(Boolean).join(" ");
}

export function timeOf(isoStr: string): string {
  const d = new Date(isoStr);
  if (Number.isNaN(d.getTime())) return "--:--";
  // Render in UTC — the contract stores all timestamps as ISO-8601 UTC and the
  // demo script refers to shift times (14:30 → 14:47) as written, so we don't
  // shift them into the viewer's local timezone.
  return d.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", hour12: false, timeZone: "UTC" });
}

export function relAge(seconds: number): string {
  if (seconds < 60) return `${Math.round(seconds)}s ago`;
  const m = Math.floor(seconds / 60);
  const s = Math.round(seconds % 60);
  return `${m}m ${s.toString().padStart(2, "0")}s ago`;
}

export function pct(n: number): string {
  return `${Math.round(n * 100)}%`;
}

export const SEVERITY_META: Record<Severity, { label: string; text: string; bg: string; ring: string; dot: string }> = {
  INFO: { label: "Info", text: "text-sev-info", bg: "bg-sev-info/12", ring: "ring-sev-info/40", dot: "bg-sev-info" },
  WARNING: {
    label: "Warning",
    text: "text-sev-warning",
    bg: "bg-sev-warning/12",
    ring: "ring-sev-warning/40",
    dot: "bg-sev-warning",
  },
  HIGH: { label: "High", text: "text-sev-high", bg: "bg-sev-high/14", ring: "ring-sev-high/40", dot: "bg-sev-high" },
  CRITICAL: {
    label: "Critical",
    text: "text-sev-critical",
    bg: "bg-sev-critical/16",
    ring: "ring-sev-critical/50",
    dot: "bg-sev-critical",
  },
};

export const PROVENANCE_META: Record<Provenance, { label: string; hint: string }> = {
  REAL: { label: "Real", hint: "Measured from a real source" },
  OBSERVED: { label: "Observed", hint: "Computed from recorded telemetry" },
  PREDICTED: { label: "Predicted", hint: "Model output — not a measurement" },
  SIMULATED: { label: "Simulated", hint: "Generated by the demo simulator" },
  ASSUMED: { label: "Assumed", hint: "Fallback estimate / default assumption" },
};

export function healthColor(state: string): string {
  switch (state) {
    case "NORMAL":
      return "text-ok";
    case "WARNING":
      return "text-sev-warning";
    case "DEGRADED":
      return "text-sev-high";
    case "CRITICAL":
      return "text-sev-critical";
    default:
      return "text-fg-muted";
  }
}
